version: '3'

services:

  web:
    image: php
    ports:
        - "80:80"
    volumes:
        - ./www:/var/www/html
    links:
        - db:db

  db:
    image: mysql
    volumes:
        - ./mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    links:
        - db:db